<?php
namespace backend\models;

use yii\base\Model;

class Xiu extends Model
{
    public $oldpassword;
    public $newpassword;
    public $password_reset;

    public function rules()
    {
        return [
            [['oldpassword','newpassword','password_reset'],'required'],
            [['password_reset'],'compare','compareAttribute'=>'newpassword','operator'=>'===','message'=>'两次密码必须一致']

        ];
//        return parent::rules(); // TODO: Change the autogenerated stub
    }
    public function  attributeLabels(){
        return [
            'oldpassword'=>'旧密码',
            'newpassword'=>'新密码',
            'password_reset'=>'重复密码'
        ];
    }
}