<?php

namespace frontend\models;

use Yii;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "member".
 *
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $email
 * @property string $tel
 * @property integer $last_login_time
 * @property integer $last_login_ip
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 */
class Member extends \yii\db\ActiveRecord implements IdentityInterface
{
    public $password;
    public $cap;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'member';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'username','password','email','tel'], 'required'],
            [['last_login_time', 'last_login_ip', 'created_at', 'updated_at'], 'integer'],
            [['username'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['password'],'string','max' => 255],
            [['password_hash', 'email'], 'string', 'max' => 100],
            [['tel'], 'string', 'max' => 11],
            [['username'], 'unique'],
            [['cap'],'captcha'],
            [['email'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => '用户名',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'email' => 'Email',
            'tel' => '电话',
            'last_login_time' => 'Last Login Time',
            'last_login_ip' => 'Last Login Ip',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    public function beforeSave($insert)
    {
        if ($insert){
            //保存添加时间
            $this->created_at = time();
            //加密密码
            $this->password_hash = \Yii::$app->security->generatePasswordHash($this->password);
            //设置auth_key
            $this->auth_key = Yii::$app->security->generateRandomString();

        }else{

            $this->uptated_at = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    //根据id主键获取用户的实例对象
    public static function findIdentity($id)
    {
        return static::findOne($id);
        // TODO: Implement findIdentity() method.
    }
//获取token登陆时的用户实例
    public static function findIdentityByAccessToken($token, $type = null)
    {
        // TODO: Implement findIdentityByAccessToken() method.
    }
//获取确定对象的id
    public function getId()
    {
        return $this->id;
        // TODO: Implement getId() method.
    }
//获取自动登陆authkey
    public function getAuthKey()
    {
        return $this->auth_key;
        // TODO: Implement getAuthKey() method.
    }

    //验证自动登陆authkey
    public function validateAuthKey($authKey)
    {
        return $authKey === $this->getAuthKey();
        // TODO: Implement validateAuthKey() method.
    }
}
